# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    environmentServiceName: 'Free Trial (0cd56ed7-146e-4d85-b06e-2c8ef96475a4)'
    providerAzureRmSubscriptionId: '0cd56ed7-146e-4d85-b06e-2c8ef96475a4'
    secureVarsFile: 'input.tfvars'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
    environmentServiceName: 'Free Trial (0cd56ed7-146e-4d85-b06e-2c8ef96475a4)'
    providerAzureRmSubscriptionId: '0cd56ed7-146e-4d85-b06e-2c8ef96475a4'
    secureVarsFile: 'input.tfvars'
    allowTelemetryCollection: true
    